### PR TITLE
backport: Add RBAC permission endpointslices/restricted in broker roles

### PR DESCRIPTION
**Pull request by SteveMattar**
- Manage v1 CRDs in the broker CRD controller (#163)
- Fix condition status check in submarinerConfigController (#164)
- Add RBAC permission endpointslices/restricted in broker roles

### CODE REVIEW

**Comment by skitt** [comment]
@SteveMattar backports for the addon shouldn’t be prepared manually; please use the Prow cherry-pick commands instead. I cherry-picked the last remaining change in https://github.com/open-cluster-management/submariner-addon/pull/217

**Comment by SteveMattar** [comment]
ACK thanks @skitt

**Pull request closed without merging**
