### PR TITLE
Enable golangci-lint deadcode linter, fix errors

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
We shouldn't merge this until https://github.com/openshift/release/pull/22322/ goes in.

**Comment by skitt** [comment]
The plugin is tested in https://github.com/open-cluster-management/submariner-addon/pull/162

**Comment by dfarrell07** [comment]
Depends on https://github.com/openshift/release/pull/21461 to add the golangci-lint job.

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
