### PR TITLE
Move helpers.ApplyManifestWork to manifestwork.Apply

### PR DESCRIPTION
**Pull request by tpantelis**
It's better to avoid lumping unrelated functions into util or helpers packages so move this function to its own package.

Also modified it to use admiral's `CreateOrUpdate`.

### CODE REVIEW

**Review by Jaanki — APPROVED** [review]

**Review by aswinsuryan — APPROVED** [review]

**Review by sridhargaddam — APPROVED** [review]

**Review by skitt — CHANGES_REQUESTED** [review]
Since this has a conflict which needs to be resolved, may I suggest moving `machineset.go` to the new package location while we’re at it?

**Comment by tpantelis** [comment]
> Since this has a conflict which needs to be resolved, may I suggest moving `machineset.go` to the new package location while we’re at it?

yeah I debated co-locating the two. I could've put `Apply` in _.../cloud/manifestwork_ but it's more generalized and not related to "cloud". OTOH, it seems `NewMachineSetDeployer` is specific to cloud? If not, I'm fine with moving it.

**Comment by skitt** [comment]
> yeah I debated co-locating the two. I could've put `Apply` in _.../cloud/manifestwork_ but it's more generalized and not related to "cloud". OTOH, it seems `NewMachineSetDeployer` is specific to cloud? If not, I'm fine with moving it.

Well, I guess the whole `MachineSetDeployer` idea is `cloud`-specific; but what bothered me really is having the same package names in two different import paths.

**Comment by tpantelis** [comment]
> > yeah I debated co-locating the two. I could've put `Apply` in _.../cloud/manifestwork_ but it's more generalized and not related to "cloud". OTOH, it seems `NewMachineSetDeployer` is specific to cloud? If not, I'm fine with moving it.
> 
> Well, I guess the whole `MachineSetDeployer` idea is `cloud`-specific; but what bothered me really is having the same package names in two different import paths.

I think that's fine - it's not uncommon. There are many util/helper packages out there under different paths.

**Review by skitt — APPROVED** [review]

**Pull request merged**
