### PR TITLE
Move SubmarinerConfig update from submarinerbrokerinfo.Get to caller

### PR DESCRIPTION
**Pull request by tpantelis**
The purpose of `submarinerbrokerinfo.Get` is to retrieve the broker info so it really shouldn't have the side effect of updating the passed `SubmarinerConfig` condition status.

### CODE REVIEW

**Comment by tpantelis** [comment]
@cmwylie19

**Comment by cmwylie19** [comment]
> @cmwylie19

lgtm

**Comment by cmwylie19** [comment]
> /cc skitt cmwylie19

/lgtm

**Pull request merged**
