### PR TITLE
Document why golangci-lint forcetypeassert is disabled

### PR DESCRIPTION
**Pull request by dfarrell07**
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by tpantelis** [comment]
I don't think there's any compelling reason to enable `forcetypeassert` - we have it disabled in other projects with the reason "_There are many unchecked type assertions that would be the result of a programming error so the reasonable recourse would be to panic anyway if checked so this doesn't seem useful_" which applies here as well. So let's just update the reason comment.

**Review by tpantelis — APPROVED** [review]

**Comment by skitt** [comment]
Please avoid approving and merging PRs which only contain your own commits in future :-/. There wasn’t anything particularly urgent about this one...

**Comment by tpantelis** [comment]
> Please avoid approving and merging PRs which only contain your own commits in future :-/. There wasn’t anything particularly urgent about this one...

This was originally @dfarrell07 commit and PR that was open for over 6 months.

**Comment by skitt** [comment]
> > Please avoid approving and merging PRs which only contain your own commits in future :-/. There wasn’t anything particularly urgent about this one...
> 
> This was originally @dfarrell07 commit and PR that was open for over 6 months.

I know, but now it only has one commit, not written by Daniel.

**Comment by skitt** [comment]
> yeah technically. But I just added doc text. We can revert it if you want.

No worries, the commit itself is fine, I would have approved it ;-).

**Pull request merged**
